# Generated by Django 5.2.12 on 2026-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
