# Generated by Django 4.2.29 on 2026-03-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.employee'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='expense_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='expenses.expenserecord'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
