# Generated by Django 5.2.12 on 2026-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_approval_updated_at_alter_approval_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('ADMIN PENDING', 'Admin Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='ADMIN PENDING', max_length=20),
        ),
    ]
