# Generated by Django 4.2.29 on 2026-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
