# Generated by Django 4.2.29 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expenselineitem_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='violation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
